project: yourProjectName

servers:
  vps1:
    host: 192.168.0.109
    user: root
    password: yourPassword
    auth: password
    port: 22

  vps2:
    host: 192.168.0.110
    user: root
    password: yourPassword
    auth: password
    port: 22

services:
  frontend:
    server: vps1
    path: /home/frontend
    commands:
      - git pull
      - npm ci
      - npm run build

  backend:
    server: vps2
    path: /home/backend
    commands:
      - git pull
      - docker build -t api .
      - docker rm -f api || true
      - docker run --name api -d -p 3000:8080 api